### ISSUE TITLE
Docs for use case of a person who just wants to get data out

### ISSUE THREAD

**Issue by Frijol** [qri-io/website#87]
I see there's some existing roadmap to build out docs, but– it would be really useful to have something more granular than a full overview of Qri. Specifically, it would be great to have a tutorial showing someone who has received a QRI link (e.g. https://app.qri.io/b5/texas_tceq_deer_park_auto_gc) proceed from there to having data downloaded to their computer.

**Comment by ramfox** [comment]
yes definitely! I think there are a bunch of tutorials needed, especially for the frontend. I'm going to create an issue tracking the tutorials I think need to be made, I'll tag you in that if you have any more opinions :)

One interesting thing about particular issue is our different views of the workflow to getting data from qri.

I personally wouldn't send someone to `app.qri.io`, I would tell them to launch the app and go straight to `/b5/texas_tceq_deer_park_auto_gc`.

Makes me wonder exactly what the function of `app.qri.io` really is. I've been thinking about it as almost like advertising for people who don't know qri or don't want to commit to downloading it just yet, rather than the way we share data among users.

But that distinction might be too... close? Maybe it would benefit us to have more functionality to app.qri.io? Or less?

**Comment by Frijol** [comment]
Yes, I think this is a really interesting thing to explore! This is coming from a specific use case I have right now, where I'm trying to give someone a link to data we saved for them, but they don't have any familiarity with Qri (or even, the decentralized web). This is not a programmer, or someone particularly interested in the technology, and their digital fluency is an unknown variable. So I can't really start with "Download this app..."

The person I'm sharing this data with might not even be the end user (though the data matters to them very much)– it's very possible that they'll need to pass it on to one or more *other* people (their tech team? Other parties I don't know about?) to get it to the person who actually wants to download the data. So essentially, I need to give them something that they understand (a URL), that they can look at and verify is more or less what they think it is (so, the overview and metadata here are really important), which also has enough information that the end user (whoever it is) can eventually access and download the data through the app *without* need for intervention or instruction from me.
